server:
  name: "Phospherus"
  port: ":2699"
  mode: "dev"

mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "phospherus"
  user: "root"
  password: "123456"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
