server:
  name: "Phospherus"
  port: ":8989"
  mode: "release"

zap:
  level: info
  format: console
  prefix: "[Phospherus]"
  director: logs
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

mysql:
  host: "phospherus-db"
  port: 3306
  dbname: "phospherus"
  user: "root"
  password: "123456"
  max_open_conns: 200
  max_idle_conns: 50

jwt:
  secret: "phospherus"
  expireTime: 3

oss:
  accessKey: ""
  secretKey: ""
  endpoint: ""
  bucket: ""
